name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Isso cria o gradlew no seu ambiente, resolvendo o erro de "file not found"
      - name: Gerar Gradle Wrapper
        run: gradle wrapper --gradle-version 8.5

      # Agora usamos o ./gradlew que acabamos de criar
      - name: Compilar APK Debug
        run: ./gradlew assembleDebug --stacktrace

      - name: Salvar APK como Artefato
        uses: actions/upload-artifact@v4
        with:
          name: FloatingButton-App
          path: app/build/outputs/apk/debug/app-debug.apk
